CREATE TABLE "submission-figshare-files" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "submission_id" uuid REFERENCES "submission",
    "file_id" uuid REFERENCES "file",
    "order" int,
    "removed" boolean
);
